sass:
  style: :compressed  # Change to :expanded for debugging

permalink: /:year/:month/:day/:title.html

url: https://devchuan.com
baseurl: ""

future: true
debug: false

# Build settings
markdown: kramdown
permalink: pretty
future: true
highlighter: rouge
linenos: true
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Disqus post comments
disqus_shortname: techmakervn

# number of posts per page. Should be a number such that total pages >= 5. Well, this 
# is my choice, there is no specific reason for this.
# Pagination Settings
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# `gems: [jekyll-paginate]`

gems:
  - jekyll-sitemap
  - jekyll-paginate-v2